version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: erp
      POSTGRES_USER: erp
      POSTGRES_PASSWORD: erp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mysql_pim:
    image: mysql:8.0
    container_name: mysql_pim
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pim
    ports:
      - "3307:3306"
    volumes:
      - mysql_pim_data:/var/lib/mysql

  mysql_magento:
    image: mysql:8.0
    container_name: mysql_magento
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    ports:
      - "3308:3306"
    volumes:
      - mysql_magento_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./magento-store/db:/docker-entrypoint-initdb.d

  redis-magento:
    image: redis:7
    container_name: redis-magento

  rabbitmq-magento:
    image: rabbitmq:3-management
    container_name: rabbitmq-magento
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: magento
      RABBITMQ_DEFAULT_PASS: magento

  erp:
    build:
      context: ./docker/erp-symfony
      dockerfile: image/Dockerfile
    container_name: erp
    volumes:
      - ./erp-symfony/src:/var/www/erp
    depends_on:
      - postgres
    expose:
      - "9000"

  pim:
    build:
      context: ./docker/pim-laravel
      dockerfile: image/Dockerfile
    container_name: pim
    volumes:
      - ./pim-laravel/src:/var/www/pim
    depends_on:
      - mysql_pim
    environment:
      DB_HOST: mysql_pim
      DB_DATABASE: pim
      DB_USERNAME: root
      DB_PASSWORD: root
    expose:
      - "9000"

  magento:
    build:
      context: ./docker/magento-store
      dockerfile: image/Dockerfile
    container_name: magento
    volumes:
      - ./magento-store/src:/var/www/magento
    depends_on:
      - mysql_magento
    environment:
      DB_HOST: mysql_magento
      DB_NAME: magento
      DB_USER: magento
      DB_PASSWORD: magento
    expose:
      - "9000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./erp-symfony/src:/var/www/erp
      - ./pim-laravel/src:/var/www/pim
      - ./magento-store/src:/var/www/magento
    depends_on:
      - erp
      - pim
      - magento

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ports:
      - "9200:9200"

volumes:
  postgres_data:
  mysql_pim_data:
  mysql_magento_data: